name: monopoly-dev
services:
  broker:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: monopoly
      POSTGRES_USER: pennybags
      POSTGRES_PASSWORD: 131044f9-0b69-4031-aad4-197901fcdcde
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: host
volumes:
  postgres-data:
  rabbitmq-data:
