name: monopoly
services:
  # web-service:
  #   image: lighttpd
  # websocket-service:
  #   build: ./backend/websocket/Dockerfile
  rest-service:
    depends_on:
      - broker
    build:
      dockerfile: ../backend/rest/Dockerfile
      context: ../backend/
    ports:
      - 8080:8080
  broker:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  # game-service:
  #   build: ./backend/game/Dockerfile
  data-service:
    depends_on:
      - db
      - broker
    build:
      dockerfile: ../backend/data/Dockerfile
      context: ../backend/
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: monopoly
      POSTGRES_USER: pennybags
      POSTGRES_PASSWORD: 131044f9-0b69-4031-aad4-197901fcdcde
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  rabbitmq-data:
